services:
  db:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - ./backend/.env
    depends_on:
      - db
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres

volumes:
  pgdata:
