-- DropForeignKey
ALTER TABLE "RFQ" DROP CONSTRAINT "RFQ_productId_fkey";

-- AddForeignKey
ALTER TABLE "RFQ" ADD CONSTRAINT "RFQ_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
